services:
  db:
    image: mariadb:10.11.2
    working_dir: /application
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb-file-format=Barracuda,
        --innodb-large-prefix=1,
        --innodb-file-per-table=1,
      ]
    ports:
      - 33406:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=latienda
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    networks:
      - symfony-template

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8060:80
    volumes:
      - .:/var/www/html/app:rw
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - symfony-template

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: d5d95fcd53207a4001dd388251e5bd7b
      DATABASE_URL: "mysql://root:admin@db:3306/latienda?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
    volumes:
      - ./:/var/www/html/app
    networks:
      - symfony-template
    depends_on:
      - db

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  symfony-template:

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
